### ISSUE TITLE
Can text in bullet points not be smaller?

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#1684]
In the new amp.dev:

Text in bullet points is smaller than other text, because of this rule:

```css
.ap--content ul {
	font-size: 0.875rem;
}
```

Can we remove this rule so that bullet point text isn't so small?

/cc @sebastianbenz @matthiasrohmer @mandarini
