### ISSUE TITLE
Paragraphs in notes lack spacing

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#1685]
There's no spacing between paragraphs in notes. Here's why:

```css
.ap-m-tip .ap-m-tip-content p {
    margin-bottom: 0
}
```

Any chance I can remove this rule?

Here's a screenshot:

![Screen Shot 2019-04-01 at 3 32 36 PM](https://user-images.githubusercontent.com/29419498/55354612-2f7b1800-5494-11e9-8c4c-0a0c90172abe.png)

**Comment by matthiasrohmer** [comment]
Please, go ahead!

**Comment by morsssss** [comment]
Thank you!

I hunted around and found this in `frontend/scss/components/molecules/tip.scss`:

```css
  &-content {
    p {
      margin-bottom: 0;
      @include txt-2;
    }
```

I removed the `margin-bottom: 0;`, but that change didn't propagate to my site.

Am I changing the wrong file or am I not building right?
