### ISSUE TITLE
Code Snippets causes page to overflow and hence messing up the width anything responsive

### ISSUE THREAD

**Issue by mkhatib** [ampproject/docs#199]
(originally filed by @simonferndriger [here](https://github.com/ampproject/amphtml/issues/5259))

On Internet Explorer 11, the width of the content area is expanded to ~3500px causing responsive elements like `amp-youtube` to take that width. (Example page where this is happening: https://www.ampproject.org/docs/get_started/about-amp.html)

I've tracked the issue down to the `<pre>` element in the content for code snippets as combined with the following style snippet:

``` css
.main {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: stretch;
    -ms-flex-align: stretch;
    align-items: stretch
}
```

![image](https://cloud.githubusercontent.com/assets/2647/18895716/98353128-84d0-11e6-94f4-c4c4607ae79e.png)
